spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 7
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        use_sql_comments: false
        jdbc:
          batch_size: 1000
          order_inserts: true
          order_updates: true
    show-sql: false
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 20
