spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 2

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        use_sql_comments: true
        jdbc:
          batch_size: 1000
          order_inserts: true
          order_updates: true
    show-sql: false

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ""
    hikari:
      register-mbeans: true
      maximum-pool-size: 30
      minimum-idle: 30
      connection-timeout: 10000
      max-lifetime: 600000
      validation-timeout: 3000
      pool-name: "lol-server-pool"
