plugins {
    id 'lolserver.web-conventions'
    id 'lolserver.persistence-conventions'
}

dependencies {
    implementation project(':module:common')
    implementation project(':module:shared')
    implementation project(':module:support:logging')

    implementation 'org.springframework.boot:spring-boot-starter-data-redis'

    // champion rate limit 에 Bucket4j 사용 (FakeChampionClientAdapter)
    implementation 'com.bucket4j:bucket4j-core:8.7.0'

    testImplementation(testFixtures(project(':module:common')))
    testImplementation 'com.tngtech.archunit:archunit-junit5:1.3.0'
}
