version: '3'

services:

  backend:
    build:
      dockerfile: Dockerfile
      context: ./
    depends_on:
      - postgres
    container_name: mmr-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
        - POSTGRES_PASSWORD=1234
        - POSTGRES_USER=postgres
    restart: unless-stopped
    container_name: mmr-db
