spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

rabbitmq:
  queue.name: mmrtr.queue
  exchange.name: mmrtr.exchange
  routing.key: mmrtr.key
