spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        use_sql_comments: true
        jdbc:
          batch_size: 1000
          order_inserts: true
          order_updates: true

    show-sql: false

  datasource:
    url: jdbc:postgresql://db:5555/postgres
    driver-class-name: org.postgresql.Driver
    username: ${USERNAME}
    password: ${PASSWORD}

  data:
    redis:
      host: redis
      port: 6379

  jackson:
    time-zone: Asia/Seoul

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers: kafka:9094

logging:
  level:
    com.example.lolserver.riot: WARN
    com.example.lolserver.aspect: WARN

server:
  port: 8085

  tomcat:
    basedir: .
    accesslog:
      enabled: true
      pattern: "%{yyyy-MM-dd HH:mm:ss}t %s [%r: %{User-Agent}i %{Referer}i] [Remote Host: %a] [Size: %b]"


riot.api.key: ${API_KEY}