spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        use_sql_comments: true

  datasource:
    url: jdbc:postgresql://localhost:5555/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234

server:
  port: 8080

