spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        use_sql_comments: true
        jdbc:
          batch_size: 1000
          order_inserts: true
          order_updates: true

    show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234

  data:
    redis:
      host: localhost
      port: 6379

  jackson:
    time-zone: Asia/Seoul

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    queue:
      name: "mmrtr.renewal"
    exchange:
      name: "mmrtr"
    routing:
      key: "mmrtr.routing"

server:
  port: 8100

riot.api.key: ${API_KEY}
management:
  endpoints:
    web:
      exposure:
        include: health
