stats:
  datasource: ${STATS_DATASOURCE:clickhouse}

bigquery:
  project-id: ${BIGQUERY_PROJECT_ID:lol-server-local}
  dataset: ${BIGQUERY_DATASET:lol_analytics}
  credentials-location: ${BIGQUERY_CREDENTIALS_LOCATION:}
