-- =====================================================
-- League Domain DDL
-- =====================================================
-- 리그, 랭킹 관련 정보를 저장하는 테이블
-- =====================================================

-- -----------------------------------------------------
-- Table: league
-- Description: 리그 정보
-- -----------------------------------------------------
CREATE TABLE league (
    league_id   VARCHAR(255)    NOT NULL,
    tier        VARCHAR(255),
    name        VARCHAR(255),
    queue       VARCHAR(255),

    CONSTRAINT pk_league PRIMARY KEY (league_id)
);

COMMENT ON TABLE league IS '리그 정보 테이블';
COMMENT ON COLUMN league.league_id IS '리그 고유 식별자';
COMMENT ON COLUMN league.tier IS '리그 티어 (CHALLENGER, GRANDMASTER, MASTER 등)';
COMMENT ON COLUMN league.name IS '리그 이름';
COMMENT ON COLUMN league.queue IS '큐 타입 (RANKED_SOLO_5x5, RANKED_FLEX_SR 등)';


-- -----------------------------------------------------
-- Table: league_summoner
-- Description: 소환사별 리그 정보
-- -----------------------------------------------------
CREATE TABLE league_summoner (
    league_summoner_id  BIGINT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    puuid               VARCHAR(255),
    queue               VARCHAR(255),
    league_id           VARCHAR(255),
    wins                INTEGER         NOT NULL,
    losses              INTEGER         NOT NULL,
    tier                VARCHAR(255),
    rank                VARCHAR(255),
    league_points       INTEGER         NOT NULL,
    absolute_points     INTEGER         NOT NULL,
    veteran             BOOLEAN         NOT NULL,
    inactive            BOOLEAN         NOT NULL,
    fresh_blood         BOOLEAN         NOT NULL,
    hot_streak          BOOLEAN         NOT NULL,
    create_at           TIMESTAMP,
    update_at           TIMESTAMP,

    CONSTRAINT pk_league_summoner PRIMARY KEY (league_summoner_id),
    CONSTRAINT unique_index_puuid_and_queue UNIQUE (puuid, queue)
);

CREATE INDEX idx_league_summoner_puuid ON league_summoner (puuid);
CREATE INDEX idx_league_summoner_league_id ON league_summoner (league_id);
CREATE INDEX idx_league_summoner_absolute_points ON league_summoner (absolute_points DESC);

COMMENT ON TABLE league_summoner IS '소환사별 리그/랭크 정보 테이블';
COMMENT ON COLUMN league_summoner.league_summoner_id IS '리그 소환사 고유 식별자';
COMMENT ON COLUMN league_summoner.puuid IS '플레이어 PUUID';
COMMENT ON COLUMN league_summoner.queue IS '큐 타입';
COMMENT ON COLUMN league_summoner.league_id IS '소속 리그 ID';
COMMENT ON COLUMN league_summoner.wins IS '승리 횟수';
COMMENT ON COLUMN league_summoner.losses IS '패배 횟수';
COMMENT ON COLUMN league_summoner.tier IS '티어 (IRON, BRONZE, SILVER, GOLD, PLATINUM, EMERALD, DIAMOND, MASTER, GRANDMASTER, CHALLENGER)';
COMMENT ON COLUMN league_summoner.rank IS '등급 (I, II, III, IV)';
COMMENT ON COLUMN league_summoner.league_points IS '리그 포인트 (LP)';
COMMENT ON COLUMN league_summoner.absolute_points IS '절대 포인트 (티어+등급+LP를 수치화)';
COMMENT ON COLUMN league_summoner.veteran IS '베테랑 여부';
COMMENT ON COLUMN league_summoner.inactive IS '비활성 상태 여부';
COMMENT ON COLUMN league_summoner.fresh_blood IS '신규 진입 여부';
COMMENT ON COLUMN league_summoner.hot_streak IS '연승 중 여부';
COMMENT ON COLUMN league_summoner.create_at IS '생성 일시';
COMMENT ON COLUMN league_summoner.update_at IS '수정 일시';


-- -----------------------------------------------------
-- Table: league_summoner_history
-- Description: 소환사 리그 정보 히스토리 (변경 이력)
-- -----------------------------------------------------
CREATE TABLE league_summoner_history (
    id                      BIGINT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    league_summoner_id      BIGINT,
    puuid                   VARCHAR(255),
    queue                   VARCHAR(255),
    league_id               VARCHAR(255),
    wins                    INTEGER         NOT NULL,
    losses                  INTEGER         NOT NULL,
    tier                    VARCHAR(255),
    rank                    VARCHAR(255),
    league_points           INTEGER         NOT NULL,
    absolute_points         BIGINT          NOT NULL,
    veteran                 BOOLEAN         NOT NULL,
    inactive                BOOLEAN         NOT NULL,
    fresh_blood             BOOLEAN         NOT NULL,
    hot_streak              BOOLEAN         NOT NULL,
    created_at              TIMESTAMP,

    CONSTRAINT pk_league_summoner_history PRIMARY KEY (id)
);

CREATE INDEX idx_league_summoner_history_puuid_queue ON league_summoner_history (puuid, queue);

COMMENT ON TABLE league_summoner_history IS '소환사 리그 정보 히스토리 테이블 (변경 이력 보관)';
COMMENT ON COLUMN league_summoner_history.id IS '히스토리 고유 식별자';
COMMENT ON COLUMN league_summoner_history.league_summoner_id IS '원본 league_summoner의 ID';
COMMENT ON COLUMN league_summoner_history.puuid IS '플레이어 PUUID';
COMMENT ON COLUMN league_summoner_history.queue IS '큐 타입';
COMMENT ON COLUMN league_summoner_history.league_id IS '소속 리그 ID';
COMMENT ON COLUMN league_summoner_history.wins IS '승리 횟수';
COMMENT ON COLUMN league_summoner_history.losses IS '패배 횟수';
COMMENT ON COLUMN league_summoner_history.tier IS '티어';
COMMENT ON COLUMN league_summoner_history.rank IS '등급';
COMMENT ON COLUMN league_summoner_history.league_points IS '리그 포인트 (LP)';
COMMENT ON COLUMN league_summoner_history.absolute_points IS '절대 포인트';
COMMENT ON COLUMN league_summoner_history.veteran IS '베테랑 여부';
COMMENT ON COLUMN league_summoner_history.inactive IS '비활성 상태 여부';
COMMENT ON COLUMN league_summoner_history.fresh_blood IS '신규 진입 여부';
COMMENT ON COLUMN league_summoner_history.hot_streak IS '연승 중 여부';
COMMENT ON COLUMN league_summoner_history.created_at IS '히스토리 생성 일시';


-- -----------------------------------------------------
-- Table: summoner_ranking
-- Description: 소환사 랭킹 정보
-- -----------------------------------------------------
CREATE TABLE summoner_ranking (
    id                  BIGINT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    puuid               VARCHAR(100)    NOT NULL,
    queue               VARCHAR(50)     NOT NULL,
    region              VARCHAR(10)     NOT NULL,
    current_rank        INTEGER         NOT NULL,
    rank_change         INTEGER,
    game_name           VARCHAR(50),
    tag_line            VARCHAR(10),
    most_champion_1     VARCHAR(50),
    most_champion_2     VARCHAR(50),
    most_champion_3     VARCHAR(50),
    wins                INTEGER         NOT NULL,
    losses              INTEGER         NOT NULL,
    win_rate            DECIMAL(5,2)    NOT NULL,
    tier                VARCHAR(20)     NOT NULL,
    rank                VARCHAR(5),
    league_points       INTEGER         NOT NULL,
    created_at          TIMESTAMP,

    CONSTRAINT pk_summoner_ranking PRIMARY KEY (id),
    CONSTRAINT unique_puuid_queue_region UNIQUE (puuid, queue, region)
);

CREATE INDEX idx_summoner_ranking_region_queue_rank ON summoner_ranking (region, queue, current_rank);
CREATE INDEX idx_summoner_ranking_current_rank ON summoner_ranking (current_rank);

COMMENT ON TABLE summoner_ranking IS '소환사 랭킹 정보 테이블';
COMMENT ON COLUMN summoner_ranking.id IS '랭킹 고유 식별자';
COMMENT ON COLUMN summoner_ranking.puuid IS '플레이어 PUUID';
COMMENT ON COLUMN summoner_ranking.queue IS '큐 타입';
COMMENT ON COLUMN summoner_ranking.region IS '서버 지역';
COMMENT ON COLUMN summoner_ranking.current_rank IS '현재 순위';
COMMENT ON COLUMN summoner_ranking.rank_change IS '순위 변동';
COMMENT ON COLUMN summoner_ranking.game_name IS '게임 내 이름';
COMMENT ON COLUMN summoner_ranking.tag_line IS '태그라인';
COMMENT ON COLUMN summoner_ranking.most_champion_1 IS '모스트 챔피언 1';
COMMENT ON COLUMN summoner_ranking.most_champion_2 IS '모스트 챔피언 2';
COMMENT ON COLUMN summoner_ranking.most_champion_3 IS '모스트 챔피언 3';
COMMENT ON COLUMN summoner_ranking.wins IS '승리 횟수';
COMMENT ON COLUMN summoner_ranking.losses IS '패배 횟수';
COMMENT ON COLUMN summoner_ranking.win_rate IS '승률 (%)';
COMMENT ON COLUMN summoner_ranking.tier IS '티어';
COMMENT ON COLUMN summoner_ranking.rank IS '등급';
COMMENT ON COLUMN summoner_ranking.league_points IS '리그 포인트 (LP)';
COMMENT ON COLUMN summoner_ranking.created_at IS '생성 일시';


-- -----------------------------------------------------
-- Table: summoner_ranking_backup
-- Description: 소환사 랭킹 백업 (순위 변동 계산용)
-- -----------------------------------------------------
CREATE TABLE summoner_ranking_backup (
    id                  BIGINT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    puuid               VARCHAR(100)    NOT NULL,
    queue               VARCHAR(50)     NOT NULL,
    region              VARCHAR(10)     NOT NULL,
    current_rank        INTEGER         NOT NULL,

    CONSTRAINT pk_summoner_ranking_backup PRIMARY KEY (id)
);

CREATE INDEX idx_summoner_ranking_backup_puuid_queue_region ON summoner_ranking_backup (puuid, queue, region);

COMMENT ON TABLE summoner_ranking_backup IS '소환사 랭킹 백업 테이블 (순위 변동 계산용)';
COMMENT ON COLUMN summoner_ranking_backup.id IS '백업 고유 식별자';
COMMENT ON COLUMN summoner_ranking_backup.puuid IS '플레이어 PUUID';
COMMENT ON COLUMN summoner_ranking_backup.queue IS '큐 타입';
COMMENT ON COLUMN summoner_ranking_backup.region IS '서버 지역';
COMMENT ON COLUMN summoner_ranking_backup.current_rank IS '현재 순위';


-- -----------------------------------------------------
-- Table: tier_cutoff
-- Description: 티어별 최소 LP 컷오프
-- -----------------------------------------------------
CREATE TABLE tier_cutoff (
    id                  BIGINT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    queue               VARCHAR(50)     NOT NULL,
    tier                VARCHAR(20)     NOT NULL,
    region              VARCHAR(10)     NOT NULL,
    min_league_points   INTEGER         NOT NULL,
    lp_change           INTEGER,
    user_count          INTEGER,
    updated_at          TIMESTAMP,
    created_at          TIMESTAMP,

    CONSTRAINT pk_tier_cutoff PRIMARY KEY (id),
    CONSTRAINT unique_queue_tier_region UNIQUE (queue, tier, region)
);

COMMENT ON TABLE tier_cutoff IS '티어별 최소 LP 컷오프 테이블';
COMMENT ON COLUMN tier_cutoff.id IS '컷오프 고유 식별자';
COMMENT ON COLUMN tier_cutoff.queue IS '큐 타입';
COMMENT ON COLUMN tier_cutoff.tier IS '티어';
COMMENT ON COLUMN tier_cutoff.region IS '서버 지역';
COMMENT ON COLUMN tier_cutoff.min_league_points IS '해당 티어 진입 최소 LP';
COMMENT ON COLUMN tier_cutoff.lp_change IS 'LP 변화량 (현재 - 이전)';
COMMENT ON COLUMN tier_cutoff.user_count IS '해당 티어 유저 수';
COMMENT ON COLUMN tier_cutoff.updated_at IS '수정 일시';
COMMENT ON COLUMN tier_cutoff.created_at IS '생성 일시';


-- -----------------------------------------------------
-- Table: tier_cutoff_backup
-- Description: 티어 커트라인 백업 (LP 변동 계산용)
-- -----------------------------------------------------
CREATE TABLE tier_cutoff_backup (
    id                  BIGINT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    queue               VARCHAR(50)     NOT NULL,
    tier                VARCHAR(20)     NOT NULL,
    region              VARCHAR(10)     NOT NULL,
    min_league_points   INTEGER         NOT NULL,
    user_count          INTEGER,

    CONSTRAINT pk_tier_cutoff_backup PRIMARY KEY (id)
);

CREATE INDEX idx_tier_cutoff_backup_queue_tier_region ON tier_cutoff_backup (queue, tier, region);

COMMENT ON TABLE tier_cutoff_backup IS '티어 커트라인 백업 테이블 (LP 변동 계산용)';
COMMENT ON COLUMN tier_cutoff_backup.id IS '백업 고유 식별자';
COMMENT ON COLUMN tier_cutoff_backup.queue IS '큐 타입';
COMMENT ON COLUMN tier_cutoff_backup.tier IS '티어';
COMMENT ON COLUMN tier_cutoff_backup.region IS '서버 지역';
COMMENT ON COLUMN tier_cutoff_backup.min_league_points IS '이전 최소 LP';
COMMENT ON COLUMN tier_cutoff_backup.user_count IS '해당 티어 유저 수';
