-- =====================================================
-- Match Domain DDL
-- =====================================================
-- 매치 정보를 저장하는 테이블
-- =====================================================

-- -----------------------------------------------------
-- Table: match
-- Description: 매치 기본 정보
-- -----------------------------------------------------
CREATE TABLE match (
    match_id                VARCHAR(255)    NOT NULL,
    data_version            VARCHAR(255),
    end_of_game_result      VARCHAR(255),
    game_creation           BIGINT          NOT NULL,
    game_duration           BIGINT          NOT NULL,
    game_end_timestamp      BIGINT          NOT NULL,
    game_start_timestamp    BIGINT          NOT NULL,
    game_id                 BIGINT          NOT NULL,
    game_mode               VARCHAR(255),
    game_name               VARCHAR(255),
    game_type               VARCHAR(255),
    game_version            VARCHAR(255),
    map_id                  INTEGER         NOT NULL,
    queue_id                INTEGER         NOT NULL,
    platform_id             VARCHAR(255),
    tournament_code         VARCHAR(255),
    season                  INTEGER         NOT NULL,
    game_create_datetime    TIMESTAMP,
    game_end_datetime       TIMESTAMP,
    game_start_datetime     TIMESTAMP,

    CONSTRAINT pk_match PRIMARY KEY (match_id)
);

CREATE INDEX idx_match_game_id ON match (game_id);
CREATE INDEX idx_match_queue_id ON match (queue_id);
CREATE INDEX idx_match_platform_id ON match (platform_id);
CREATE INDEX idx_match_season ON match (season);
CREATE INDEX idx_match_game_create_datetime ON match (game_create_datetime DESC);

COMMENT ON TABLE match IS '매치 기본 정보 테이블';
COMMENT ON COLUMN match.match_id IS '매치 고유 식별자 (예: KR_1234567890)';
COMMENT ON COLUMN match.data_version IS '데이터 버전';
COMMENT ON COLUMN match.end_of_game_result IS '게임 종료 결과';
COMMENT ON COLUMN match.game_creation IS '게임 생성 타임스탬프 (epoch milliseconds)';
COMMENT ON COLUMN match.game_duration IS '게임 진행 시간 (초)';
COMMENT ON COLUMN match.game_end_timestamp IS '게임 종료 타임스탬프 (epoch milliseconds)';
COMMENT ON COLUMN match.game_start_timestamp IS '게임 시작 타임스탬프 (epoch milliseconds)';
COMMENT ON COLUMN match.game_id IS '게임 ID';
COMMENT ON COLUMN match.game_mode IS '게임 모드 (CLASSIC, ARAM 등)';
COMMENT ON COLUMN match.game_name IS '게임 이름';
COMMENT ON COLUMN match.game_type IS '게임 타입 (MATCHED_GAME, CUSTOM_GAME 등)';
COMMENT ON COLUMN match.game_version IS '게임 버전';
COMMENT ON COLUMN match.map_id IS '맵 ID';
COMMENT ON COLUMN match.queue_id IS '큐 ID';
COMMENT ON COLUMN match.platform_id IS '플랫폼 ID (KR, NA1 등)';
COMMENT ON COLUMN match.tournament_code IS '토너먼트 코드';
COMMENT ON COLUMN match.season IS '시즌 번호';
COMMENT ON COLUMN match.game_create_datetime IS '게임 생성 일시';
COMMENT ON COLUMN match.game_end_datetime IS '게임 종료 일시';
COMMENT ON COLUMN match.game_start_datetime IS '게임 시작 일시';


-- -----------------------------------------------------
-- Table: match_summoner
-- Description: 매치 참가 소환사 정보
-- -----------------------------------------------------
CREATE TABLE match_summoner (
    match_sumoner_id                    BIGINT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    puuid                               VARCHAR(255),
    match_id                            VARCHAR(255),
    summoner_id                         VARCHAR(255),

    -- 유저 정보
    riot_id_game_name                   VARCHAR(255),
    riot_id_tagline                     VARCHAR(255),
    profile_icon                        INTEGER         NOT NULL,
    summoner_name                       VARCHAR(255),
    participant_id                      INTEGER         NOT NULL,

    -- 챔피언, 룬, 스펠 정보
    champ_level                         INTEGER         NOT NULL,
    champion_id                         INTEGER         NOT NULL,
    champion_name                       VARCHAR(255),
    lane                                VARCHAR(255),
    champ_experience                    INTEGER         NOT NULL,
    role                                VARCHAR(255),
    spell1_casts                        INTEGER         NOT NULL,
    spell2_casts                        INTEGER         NOT NULL,
    spell3_casts                        INTEGER         NOT NULL,
    spell4_casts                        INTEGER         NOT NULL,
    summoner1_casts                     INTEGER         NOT NULL,
    summoner1_id                        INTEGER         NOT NULL,
    summoner2_casts                     INTEGER         NOT NULL,
    summoner2_id                        INTEGER         NOT NULL,
    summoner_level                      INTEGER         NOT NULL,
    bounty_level                        INTEGER         NOT NULL,

    -- 킬 관련
    kills                               INTEGER         NOT NULL,
    assists                             INTEGER         NOT NULL,
    deaths                              INTEGER         NOT NULL,
    double_kills                        INTEGER         NOT NULL,
    triple_kills                        INTEGER         NOT NULL,
    quadra_kills                        INTEGER         NOT NULL,
    penta_kills                         INTEGER         NOT NULL,
    unreal_kills                        INTEGER         NOT NULL,

    -- 케인 전용
    champion_transform                  INTEGER         NOT NULL,

    -- 골드 관련, 아이템 구매
    gold_earned                         INTEGER         NOT NULL,
    gold_spent                          INTEGER         NOT NULL,
    items_purchased                     INTEGER         NOT NULL,
    consumables_purchased               INTEGER         NOT NULL,

    -- 미니언 관련
    neutral_minions_killed              INTEGER         NOT NULL,
    total_minions_killed                INTEGER         NOT NULL,
    objectives_stolen                   INTEGER         NOT NULL,
    objectives_stolen_assists           INTEGER         NOT NULL,

    -- 와드 관련
    detector_wards_placed               INTEGER         NOT NULL,
    sight_wards_bought_in_game          INTEGER         NOT NULL,
    vision_score                        INTEGER         NOT NULL,
    vision_wards_bought_in_game         INTEGER         NOT NULL,
    wards_killed                        INTEGER         NOT NULL,
    wards_placed                        INTEGER         NOT NULL,

    -- 오브젝트 관련
    baron_kills                         INTEGER         NOT NULL,
    dragon_kills                        INTEGER         NOT NULL,
    first_blood_assist                  BOOLEAN         NOT NULL,
    first_blood_kill                    BOOLEAN         NOT NULL,
    first_tower_assist                  BOOLEAN         NOT NULL,
    first_tower_kill                    BOOLEAN         NOT NULL,
    inhibitor_kills                     INTEGER         NOT NULL,
    inhibitor_takedowns                 INTEGER         NOT NULL,
    inhibitors_lost                     INTEGER         NOT NULL,
    nexus_kills                         INTEGER         NOT NULL,
    nexus_takedowns                     INTEGER         NOT NULL,
    nexus_lost                          INTEGER         NOT NULL,
    turret_kills                        INTEGER         NOT NULL,
    turret_takedowns                    INTEGER         NOT NULL,
    turrets_lost                        INTEGER         NOT NULL,

    -- 게임 정보
    game_ended_in_early_surrender       BOOLEAN         NOT NULL,
    game_ended_in_surrender             BOOLEAN         NOT NULL,
    team_early_surrendered              BOOLEAN         NOT NULL,
    team_position                       VARCHAR(255),
    team_id                             INTEGER         NOT NULL,
    win                                 BOOLEAN         NOT NULL,
    time_played                         INTEGER         NOT NULL,
    individual_position                 VARCHAR(255),

    -- 피해, 받은 피해, 회복, CC
    magic_damage_dealt                  INTEGER         NOT NULL,
    magic_damage_dealt_to_champions     INTEGER         NOT NULL,
    magic_damage_taken                  INTEGER         NOT NULL,
    physical_damage_dealt               INTEGER         NOT NULL,
    physical_damage_dealt_to_champions  INTEGER         NOT NULL,
    physical_damage_taken               INTEGER         NOT NULL,
    damage_dealt_to_buildings           INTEGER         NOT NULL,
    damage_dealt_to_objectives          INTEGER         NOT NULL,
    damage_dealt_to_turrets             INTEGER         NOT NULL,
    damage_self_mitigated               INTEGER         NOT NULL,
    total_damage_dealt                  INTEGER         NOT NULL,
    total_damage_dealt_to_champions     INTEGER         NOT NULL,
    total_damage_shielded_on_teammates  INTEGER         NOT NULL,
    total_damage_taken                  INTEGER         NOT NULL,
    true_damage_dealt                   INTEGER         NOT NULL,
    true_damage_dealt_to_champions      INTEGER         NOT NULL,
    true_damage_taken                   INTEGER         NOT NULL,
    total_heal                          INTEGER         NOT NULL,
    total_heals_on_teammates            INTEGER         NOT NULL,
    total_timeccdealt                   INTEGER         NOT NULL,
    total_time_spent_dead               INTEGER         NOT NULL,
    total_units_healed                  INTEGER         NOT NULL,
    time_ccing_others                   INTEGER         NOT NULL,
    killing_sprees                      INTEGER         NOT NULL,
    largest_critical_strike             INTEGER         NOT NULL,
    largest_killing_spree               INTEGER         NOT NULL,
    largest_multi_kill                  INTEGER         NOT NULL,
    longest_time_spent_living           INTEGER         NOT NULL,

    -- 아레나/핑 관련
    all_in_pings                        INTEGER         NOT NULL,
    assist_me_pings                     INTEGER         NOT NULL,
    command_pings                       INTEGER         NOT NULL,
    eligible_for_progression            BOOLEAN         NOT NULL,
    enemy_missing_pings                 INTEGER         NOT NULL,
    enemy_vision_pings                  INTEGER         NOT NULL,
    hold_pings                          INTEGER         NOT NULL,
    get_back_pings                      INTEGER         NOT NULL,
    need_vision_pings                   INTEGER         NOT NULL,
    on_my_way_pings                     INTEGER         NOT NULL,
    player_score0                       INTEGER         NOT NULL,
    player_score1                       INTEGER         NOT NULL,
    player_score2                       INTEGER         NOT NULL,
    player_score3                       INTEGER         NOT NULL,
    player_score4                       INTEGER         NOT NULL,
    player_score5                       INTEGER         NOT NULL,
    player_score6                       INTEGER         NOT NULL,
    player_score7                       INTEGER         NOT NULL,
    player_score8                       INTEGER         NOT NULL,
    player_score9                       INTEGER         NOT NULL,
    player_score10                      INTEGER         NOT NULL,
    player_score11                      INTEGER         NOT NULL,
    placement                           INTEGER         NOT NULL,
    player_augment1                     INTEGER         NOT NULL,
    player_augment2                     INTEGER         NOT NULL,
    player_augment3                     INTEGER         NOT NULL,
    player_augment4                     INTEGER         NOT NULL,
    player_subteam_id                   INTEGER         NOT NULL,
    push_pings                          INTEGER         NOT NULL,
    riot_id_name                        VARCHAR(255),
    subteam_placement                   INTEGER         NOT NULL,
    total_ally_jungle_minions_killed    INTEGER         NOT NULL,
    total_enemy_jungle_minions_killed   INTEGER         NOT NULL,
    vision_cleared_pings                INTEGER         NOT NULL,

    -- Embedded: ItemValue
    item0                               INTEGER         NOT NULL,
    item1                               INTEGER         NOT NULL,
    item2                               INTEGER         NOT NULL,
    item3                               INTEGER         NOT NULL,
    item4                               INTEGER         NOT NULL,
    item5                               INTEGER         NOT NULL,
    item6                               INTEGER         NOT NULL,

    -- Embedded: StatValue (스탯 룬)
    defense                             INTEGER         NOT NULL,
    flex                                INTEGER         NOT NULL,
    offense                             INTEGER         NOT NULL,

    -- Embedded: StyleValue (룬 스타일)
    primary_rune_id                     INTEGER         NOT NULL,
    primary_rune_ids                    VARCHAR(255),
    secondary_rune_id                   INTEGER         NOT NULL,
    secondary_rune_ids                  VARCHAR(255),

    CONSTRAINT pk_match_summoner PRIMARY KEY (match_sumoner_id),
    CONSTRAINT unique_index_match_id_and_puuid UNIQUE (puuid, match_id)
);

CREATE INDEX idx_match_summoner_puuid ON match_summoner (puuid);
CREATE INDEX idx_match_summoner_match_id ON match_summoner (match_id);
CREATE INDEX idx_match_summoner_champion_id ON match_summoner (champion_id);

COMMENT ON TABLE match_summoner IS '매치 참가 소환사 정보 테이블';
COMMENT ON COLUMN match_summoner.match_sumoner_id IS '매치 소환사 고유 식별자';
COMMENT ON COLUMN match_summoner.puuid IS '플레이어 PUUID';
COMMENT ON COLUMN match_summoner.match_id IS '매치 ID';
COMMENT ON COLUMN match_summoner.champion_id IS '사용 챔피언 ID';
COMMENT ON COLUMN match_summoner.champion_name IS '사용 챔피언 이름';
COMMENT ON COLUMN match_summoner.team_id IS '팀 ID (100: 블루, 200: 레드)';
COMMENT ON COLUMN match_summoner.win IS '승리 여부';
COMMENT ON COLUMN match_summoner.kills IS '킬 수';
COMMENT ON COLUMN match_summoner.deaths IS '데스 수';
COMMENT ON COLUMN match_summoner.assists IS '어시스트 수';


-- -----------------------------------------------------
-- Table: match_team
-- Description: 매치 팀 정보
-- -----------------------------------------------------
CREATE TABLE match_team (
    id                  BIGINT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    match_id            VARCHAR(255),
    team_id             INTEGER         NOT NULL,
    win                 BOOLEAN         NOT NULL,

    -- 오브젝트 정보
    baron_first         BOOLEAN         NOT NULL,
    baron_kills         INTEGER         NOT NULL,
    champion_first      BOOLEAN         NOT NULL,
    champion_kills      INTEGER         NOT NULL,
    dragon_first        BOOLEAN         NOT NULL,
    dragon_kills        INTEGER         NOT NULL,
    inhibitor_first     BOOLEAN         NOT NULL,
    inhibitor_kills     INTEGER         NOT NULL,
    rift_herald_first   BOOLEAN         NOT NULL,
    rift_herald_kills   INTEGER         NOT NULL,
    tower_first         BOOLEAN         NOT NULL,
    tower_kills         INTEGER         NOT NULL,

    -- 밴 정보
    champion1_id        INTEGER         NOT NULL,
    pick1_turn          INTEGER         NOT NULL,
    champion2_id        INTEGER         NOT NULL,
    pick2_turn          INTEGER         NOT NULL,
    champion3_id        INTEGER         NOT NULL,
    pick3_turn          INTEGER         NOT NULL,
    champion4_id        INTEGER         NOT NULL,
    pick4_turn          INTEGER         NOT NULL,
    champion5_id        INTEGER         NOT NULL,
    pick5_turn          INTEGER         NOT NULL,

    CONSTRAINT pk_match_team PRIMARY KEY (id),
    CONSTRAINT unique_index_match_id_and_team_id UNIQUE (match_id, team_id)
);

CREATE INDEX idx_match_team_match_id ON match_team (match_id);

COMMENT ON TABLE match_team IS '매치 팀 정보 테이블';
COMMENT ON COLUMN match_team.id IS '매치 팀 고유 식별자';
COMMENT ON COLUMN match_team.match_id IS '매치 ID';
COMMENT ON COLUMN match_team.team_id IS '팀 ID (100: 블루, 200: 레드)';
COMMENT ON COLUMN match_team.win IS '승리 여부';
COMMENT ON COLUMN match_team.baron_first IS '첫 바론 획득 여부';
COMMENT ON COLUMN match_team.baron_kills IS '바론 처치 횟수';
COMMENT ON COLUMN match_team.dragon_first IS '첫 드래곤 획득 여부';
COMMENT ON COLUMN match_team.dragon_kills IS '드래곤 처치 횟수';
COMMENT ON COLUMN match_team.champion1_id IS '첫 번째 밴 챔피언 ID';


-- -----------------------------------------------------
-- Table: challenges
-- Description: 매치 챌린지 데이터
-- -----------------------------------------------------
CREATE TABLE challenges (
    id                                              BIGINT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    puuid                                           VARCHAR(255),
    match_id                                        VARCHAR(255),

    assist_streak_count12                           INTEGER         NOT NULL,
    infernal_scale_pickup                           INTEGER         NOT NULL,
    ability_uses                                    INTEGER         NOT NULL,
    aces_before15_minutes                           INTEGER         NOT NULL,
    allied_jungle_monster_kills                     INTEGER         NOT NULL,
    baron_takedowns                                 INTEGER         NOT NULL,
    blast_cone_opposite_opponent_count              INTEGER         NOT NULL,
    bounty_gold                                     INTEGER         NOT NULL,
    buffs_stolen                                    INTEGER         NOT NULL,
    complete_support_quest_in_time                  INTEGER         NOT NULL,
    control_ward_time_coverage_in_river_or_enemy_half DOUBLE PRECISION NOT NULL,
    control_wards_placed                            INTEGER         NOT NULL,
    damage_per_minute                               DOUBLE PRECISION NOT NULL,
    damage_taken_on_team_percentage                 DOUBLE PRECISION NOT NULL,
    danced_with_rift_herald                         INTEGER         NOT NULL,
    deaths_by_enemy_champs                          INTEGER         NOT NULL,
    dodge_skill_shots_small_window                  INTEGER         NOT NULL,
    double_aces                                     INTEGER         NOT NULL,
    dragon_takedowns                                INTEGER         NOT NULL,
    early_laning_phase_gold_exp_advantage           INTEGER         NOT NULL,
    effective_heal_and_shielding                    INTEGER         NOT NULL,
    elder_dragon_kills_with_opposing_soul           INTEGER         NOT NULL,
    elder_dragon_multikills                         INTEGER         NOT NULL,
    enemy_champion_immobilizations                  INTEGER         NOT NULL,
    enemy_jungle_monster_kills                      INTEGER         NOT NULL,
    epic_monster_kills_near_enemy_jungler           INTEGER         NOT NULL,
    epic_monster_kills_within30_seconds_of_spawn    INTEGER         NOT NULL,
    epic_monster_steals                             INTEGER         NOT NULL,
    epic_monster_stolen_without_smite               INTEGER         NOT NULL,
    first_turret_killed                             INTEGER         NOT NULL,
    first_turret_killed_time                        DOUBLE PRECISION NOT NULL,
    fist_bump_participation                         INTEGER         NOT NULL,
    flawless_aces                                   INTEGER         NOT NULL,
    full_team_takedown                              INTEGER         NOT NULL,
    game_length                                     DOUBLE PRECISION NOT NULL,
    get_takedowns_in_all_lanes_early_jungle_as_laner INTEGER        NOT NULL,
    gold_per_minute                                 DOUBLE PRECISION NOT NULL,
    had_open_nexus                                  INTEGER         NOT NULL,
    immobilize_and_kill_with_ally                   INTEGER         NOT NULL,
    initial_buff_count                              INTEGER         NOT NULL,
    initial_crab_count                              INTEGER         NOT NULL,
    jungle_cs_before10_minutes                      INTEGER         NOT NULL,
    jungler_takedowns_near_damaged_epic_monster     INTEGER         NOT NULL,
    k_turrets_destroyed_before_plates_fall          INTEGER         NOT NULL,
    kda                                             DOUBLE PRECISION NOT NULL,
    kill_after_hidden_with_ally                     INTEGER         NOT NULL,
    kill_participation                              DOUBLE PRECISION NOT NULL,
    killed_champ_took_full_team_damage_survived     INTEGER         NOT NULL,
    killing_sprees                                  INTEGER         NOT NULL,
    kills_near_enemy_turret                         INTEGER         NOT NULL,
    kills_on_other_lanes_early_jungle_as_laner      INTEGER         NOT NULL,
    kills_on_recently_healed_by_aram_pack           INTEGER         NOT NULL,
    kills_under_own_turret                          INTEGER         NOT NULL,
    kills_with_help_from_epic_monster               INTEGER         NOT NULL,
    knock_enemy_into_team_and_kill                  INTEGER         NOT NULL,
    land_skill_shots_early_game                     INTEGER         NOT NULL,
    lane_minions_first10_minutes                    INTEGER         NOT NULL,
    laning_phase_gold_exp_advantage                 INTEGER         NOT NULL,
    legendary_count                                 INTEGER         NOT NULL,
    legendary_item_used                             VARCHAR(2000),
    lost_an_inhibitor                               INTEGER         NOT NULL,
    max_cs_advantage_on_lane_opponent               INTEGER         NOT NULL,
    max_kill_deficit                                INTEGER         NOT NULL,
    max_level_lead_lane_opponent                    INTEGER         NOT NULL,
    mejais_full_stack_in_time                       INTEGER         NOT NULL,
    more_enemy_jungle_than_opponent                 INTEGER         NOT NULL,
    multi_kill_one_spell                            INTEGER         NOT NULL,
    multi_turret_rift_herald_count                  INTEGER         NOT NULL,
    multikills                                      INTEGER         NOT NULL,
    multikills_after_aggressive_flash               INTEGER         NOT NULL,
    outer_turret_executes_before10_minutes          INTEGER         NOT NULL,
    outnumbered_kills                               INTEGER         NOT NULL,
    outnumbered_nexus_kill                          INTEGER         NOT NULL,
    perfect_dragon_souls_taken                      INTEGER         NOT NULL,
    perfect_game                                    INTEGER         NOT NULL,
    pick_kill_with_ally                             INTEGER         NOT NULL,
    played_champ_select_position                    INTEGER         NOT NULL,
    poro_explosions                                 INTEGER         NOT NULL,
    quick_cleanse                                   INTEGER         NOT NULL,
    quick_first_turret                              INTEGER         NOT NULL,
    quick_solo_kills                                INTEGER         NOT NULL,
    rift_herald_takedowns                           INTEGER         NOT NULL,
    save_ally_from_death                            INTEGER         NOT NULL,
    scuttle_crab_kills                              INTEGER         NOT NULL,
    skillshots_dodged                               INTEGER         NOT NULL,
    skillshots_hit                                  INTEGER         NOT NULL,
    snowballs_hit                                   INTEGER         NOT NULL,
    solo_baron_kills                                INTEGER         NOT NULL,
    solo_kills                                      INTEGER         NOT NULL,
    stealth_wards_placed                            INTEGER         NOT NULL,
    survived_single_digit_hp_count                  INTEGER         NOT NULL,
    survived_three_immobilizes_in_fight             INTEGER         NOT NULL,
    takedown_on_first_turret                        INTEGER         NOT NULL,
    takedowns                                       INTEGER         NOT NULL,
    takedowns_after_gaining_level_advantage         INTEGER         NOT NULL,
    takedowns_before_jungle_minion_spawn            INTEGER         NOT NULL,
    takedowns_first_x_minutes                       INTEGER         NOT NULL,
    takedowns_in_alcove                             INTEGER         NOT NULL,
    takedowns_in_enemy_fountain                     INTEGER         NOT NULL,
    team_baron_kills                                INTEGER         NOT NULL,
    team_damage_percentage                          DOUBLE PRECISION NOT NULL,
    team_elder_dragon_kills                         INTEGER         NOT NULL,
    team_rift_herald_kills                          INTEGER         NOT NULL,
    took_large_damage_survived                      INTEGER         NOT NULL,
    turret_plates_taken                             INTEGER         NOT NULL,
    turret_takedowns                                INTEGER         NOT NULL,
    turrets_taken_with_rift_herald                  INTEGER         NOT NULL,
    twenty_minions_in3_seconds_count                INTEGER         NOT NULL,
    two_wards_one_sweeper_count                     INTEGER         NOT NULL,
    unseen_recalls                                  INTEGER         NOT NULL,
    vision_score_advantage_lane_opponent            DOUBLE PRECISION NOT NULL,
    vision_score_per_minute                         DOUBLE PRECISION NOT NULL,
    void_monster_kill                               INTEGER         NOT NULL,
    ward_takedowns                                  INTEGER         NOT NULL,
    ward_takedowns_before20m                        INTEGER         NOT NULL,
    wards_guarded                                   INTEGER         NOT NULL,

    CONSTRAINT pk_challenges PRIMARY KEY (id),
    CONSTRAINT unique_index_puuid_and_match_id UNIQUE (puuid, match_id)
);

CREATE INDEX idx_challenges_puuid ON challenges (puuid);
CREATE INDEX idx_challenges_match_id ON challenges (match_id);

COMMENT ON TABLE challenges IS '매치 챌린지 데이터 테이블';
COMMENT ON COLUMN challenges.id IS '챌린지 고유 식별자';
COMMENT ON COLUMN challenges.puuid IS '플레이어 PUUID';
COMMENT ON COLUMN challenges.match_id IS '매치 ID';
COMMENT ON COLUMN challenges.kda IS 'K/D/A 비율';
COMMENT ON COLUMN challenges.kill_participation IS '킬 관여율';
COMMENT ON COLUMN challenges.team_damage_percentage IS '팀 딜량 퍼센트';
COMMENT ON COLUMN challenges.vision_score_per_minute IS '분당 시야 점수';
