-- =====================================================
-- Version Domain DDL
-- =====================================================
-- 패치 버전 및 패치 노트 정보를 저장하는 테이블
-- =====================================================

-- -----------------------------------------------------
-- Table: patch_version
-- Description: 패치 버전 정보
-- -----------------------------------------------------
CREATE TABLE patch_version (
    version_id      BIGINT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    version_value   VARCHAR(20)     NOT NULL,
    created_at      TIMESTAMP,

    CONSTRAINT pk_patch_version PRIMARY KEY (version_id)
);

CREATE UNIQUE INDEX idx_patch_version_value ON patch_version (version_value);

COMMENT ON TABLE patch_version IS '패치 버전 정보 테이블';
COMMENT ON COLUMN patch_version.version_id IS '버전 고유 식별자';
COMMENT ON COLUMN patch_version.version_value IS '버전 값 (예: 14.1.1, 14.2.1)';
COMMENT ON COLUMN patch_version.created_at IS '생성 일시';


-- -----------------------------------------------------
-- Table: patch_note
-- Description: 패치 노트 정보
-- -----------------------------------------------------
CREATE TABLE patch_note (
    version_id      VARCHAR(255)    NOT NULL,
    title           VARCHAR(255)    NOT NULL,
    content         JSONB,
    patch_url       VARCHAR(255),
    created_at      TIMESTAMP,

    CONSTRAINT pk_patch_note PRIMARY KEY (version_id)
);

COMMENT ON TABLE patch_note IS '패치 노트 정보 테이블';
COMMENT ON COLUMN patch_note.version_id IS '버전 식별자 (예: 14.1, 14.2)';
COMMENT ON COLUMN patch_note.title IS '패치 노트 제목';
COMMENT ON COLUMN patch_note.content IS '패치 노트 내용 (JSON 형식)';
COMMENT ON COLUMN patch_note.patch_url IS '패치 노트 URL';
COMMENT ON COLUMN patch_note.created_at IS '생성 일시';
