-- =====================================================
-- Champion Stat Domain DDL
-- =====================================================
-- 챔피언별 사전 집계 통계 테이블
-- 아이템 메타데이터 및 6개 집계 테이블로 구성
-- =====================================================


-- -----------------------------------------------------
-- Table: item_metadata
-- Description: 아이템 분류 메타데이터
-- -----------------------------------------------------
CREATE TABLE item_metadata (
    item_id         INTEGER         NOT NULL,
    item_name       VARCHAR(255)    NOT NULL,
    item_category   VARCHAR(50)     NOT NULL,
    game_version    VARCHAR(20),

    CONSTRAINT pk_item_metadata PRIMARY KEY (item_id)
);

CREATE INDEX idx_item_metadata_category ON item_metadata (item_category);
CREATE INDEX idx_item_metadata_version ON item_metadata (game_version);

COMMENT ON TABLE item_metadata IS '아이템 분류 메타데이터 테이블';
COMMENT ON COLUMN item_metadata.item_id IS 'RIOT 아이템 ID';
COMMENT ON COLUMN item_metadata.item_name IS '아이템 이름';
COMMENT ON COLUMN item_metadata.item_category IS '아이템 분류 (STARTER, BOOTS, LEGENDARY, CONSUMABLE, TRINKET)';
COMMENT ON COLUMN item_metadata.game_version IS '적용 패치 버전 (NULL이면 전 패치 공통)';


-- -----------------------------------------------------
-- Table: champion_stat_summary
-- Description: 챔피언 기본 통계 (승률, 픽률, 밴률, 평균 지표)
-- -----------------------------------------------------
CREATE TABLE champion_stat_summary (
    id                          BIGINT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    champion_id                 INTEGER         NOT NULL,
    team_position               VARCHAR(20)     NOT NULL,
    season                      INTEGER         NOT NULL,
    tier_group                  VARCHAR(30)     NOT NULL,
    platform_id                 VARCHAR(10)     NOT NULL,
    queue_id                    INTEGER         NOT NULL,
    game_version                VARCHAR(20)     NOT NULL,
    total_games                 INTEGER         NOT NULL,
    wins                        INTEGER         NOT NULL,
    total_bans                  INTEGER         NOT NULL,
    total_matches_in_dimension  INTEGER         NOT NULL,
    avg_kills                   DECIMAL(5,2)    NOT NULL,
    avg_deaths                  DECIMAL(5,2)    NOT NULL,
    avg_assists                 DECIMAL(5,2)    NOT NULL,
    avg_cs                      DECIMAL(7,2)    NOT NULL,
    avg_gold                    DECIMAL(9,2)    NOT NULL,

    CONSTRAINT pk_champion_stat_summary PRIMARY KEY (id)
);

CREATE UNIQUE INDEX idx_champion_stat_summary_dim ON champion_stat_summary (
    champion_id, team_position, season, tier_group, platform_id, queue_id, game_version
);
CREATE INDEX idx_champion_stat_summary_champion ON champion_stat_summary (champion_id);
CREATE INDEX idx_champion_stat_summary_season_queue ON champion_stat_summary (season, queue_id);

COMMENT ON TABLE champion_stat_summary IS '챔피언 기본 통계 테이블';
COMMENT ON COLUMN champion_stat_summary.id IS '고유 식별자';
COMMENT ON COLUMN champion_stat_summary.champion_id IS '챔피언 ID';
COMMENT ON COLUMN champion_stat_summary.team_position IS '라인 (TOP, JUNGLE, MIDDLE, BOTTOM, UTILITY)';
COMMENT ON COLUMN champion_stat_summary.season IS '시즌 번호';
COMMENT ON COLUMN champion_stat_summary.tier_group IS '티어 그룹 (ALL, EMERALD_PLUS, DIAMOND_PLUS, MASTER_PLUS)';
COMMENT ON COLUMN champion_stat_summary.platform_id IS '지역 (KR, ALL 등)';
COMMENT ON COLUMN champion_stat_summary.queue_id IS '큐 ID (420: 솔로랭크)';
COMMENT ON COLUMN champion_stat_summary.game_version IS '패치 버전 (major.minor)';
COMMENT ON COLUMN champion_stat_summary.total_games IS '총 판수';
COMMENT ON COLUMN champion_stat_summary.wins IS '승리 수';
COMMENT ON COLUMN champion_stat_summary.total_bans IS '밴 수';
COMMENT ON COLUMN champion_stat_summary.total_matches_in_dimension IS '해당 차원 전체 판수 (픽률 계산용)';
COMMENT ON COLUMN champion_stat_summary.avg_kills IS '평균 킬';
COMMENT ON COLUMN champion_stat_summary.avg_deaths IS '평균 데스';
COMMENT ON COLUMN champion_stat_summary.avg_assists IS '평균 어시스트';
COMMENT ON COLUMN champion_stat_summary.avg_cs IS '평균 CS';
COMMENT ON COLUMN champion_stat_summary.avg_gold IS '평균 골드';


-- -----------------------------------------------------
-- Table: champion_rune_stat
-- Description: 챔피언 룬 조합 통계
-- -----------------------------------------------------
CREATE TABLE champion_rune_stat (
    id                  BIGINT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    champion_id         INTEGER         NOT NULL,
    team_position       VARCHAR(20)     NOT NULL,
    season              INTEGER         NOT NULL,
    tier_group          VARCHAR(30)     NOT NULL,
    platform_id         VARCHAR(10)     NOT NULL,
    queue_id            INTEGER         NOT NULL,
    game_version        VARCHAR(20)     NOT NULL,
    primary_rune_id     INTEGER         NOT NULL,
    primary_rune_ids    VARCHAR(255)    NOT NULL,
    secondary_rune_id   INTEGER         NOT NULL,
    secondary_rune_ids  VARCHAR(255)    NOT NULL,
    stat_offense        INTEGER         NOT NULL,
    stat_flex           INTEGER         NOT NULL,
    stat_defense        INTEGER         NOT NULL,
    games               INTEGER         NOT NULL,
    wins                INTEGER         NOT NULL,

    CONSTRAINT pk_champion_rune_stat PRIMARY KEY (id)
);

CREATE UNIQUE INDEX idx_champion_rune_stat_dim ON champion_rune_stat (
    champion_id, team_position, season, tier_group, platform_id, queue_id, game_version,
    primary_rune_id, primary_rune_ids, secondary_rune_id, secondary_rune_ids,
    stat_offense, stat_flex, stat_defense
);
CREATE INDEX idx_champion_rune_stat_champion ON champion_rune_stat (champion_id, team_position);
CREATE INDEX idx_champion_rune_stat_season_queue ON champion_rune_stat (season, queue_id);

COMMENT ON TABLE champion_rune_stat IS '챔피언 룬 조합 통계 테이블';
COMMENT ON COLUMN champion_rune_stat.id IS '고유 식별자';
COMMENT ON COLUMN champion_rune_stat.champion_id IS '챔피언 ID';
COMMENT ON COLUMN champion_rune_stat.team_position IS '라인';
COMMENT ON COLUMN champion_rune_stat.season IS '시즌 번호';
COMMENT ON COLUMN champion_rune_stat.tier_group IS '티어 그룹';
COMMENT ON COLUMN champion_rune_stat.platform_id IS '지역';
COMMENT ON COLUMN champion_rune_stat.queue_id IS '큐 ID';
COMMENT ON COLUMN champion_rune_stat.game_version IS '패치 버전';
COMMENT ON COLUMN champion_rune_stat.primary_rune_id IS '주 룬 트리 ID (ex: 8400 결의)';
COMMENT ON COLUMN champion_rune_stat.primary_rune_ids IS '주 룬 세부 선택 CSV (ex: "8437,8446,8444,8451")';
COMMENT ON COLUMN champion_rune_stat.secondary_rune_id IS '보조 룬 트리 ID';
COMMENT ON COLUMN champion_rune_stat.secondary_rune_ids IS '보조 룬 세부 선택 CSV';
COMMENT ON COLUMN champion_rune_stat.stat_offense IS '능력치 파편 - 공격';
COMMENT ON COLUMN champion_rune_stat.stat_flex IS '능력치 파편 - 유연';
COMMENT ON COLUMN champion_rune_stat.stat_defense IS '능력치 파편 - 방어';
COMMENT ON COLUMN champion_rune_stat.games IS '판수';
COMMENT ON COLUMN champion_rune_stat.wins IS '승수';


-- -----------------------------------------------------
-- Table: champion_spell_stat
-- Description: 챔피언 소환사 주문 통계
-- -----------------------------------------------------
CREATE TABLE champion_spell_stat (
    id              BIGINT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    champion_id     INTEGER         NOT NULL,
    team_position   VARCHAR(20)     NOT NULL,
    season          INTEGER         NOT NULL,
    tier_group      VARCHAR(30)     NOT NULL,
    platform_id     VARCHAR(10)     NOT NULL,
    queue_id        INTEGER         NOT NULL,
    game_version    VARCHAR(20)     NOT NULL,
    spell1_id       INTEGER         NOT NULL,
    spell2_id       INTEGER         NOT NULL,
    games           INTEGER         NOT NULL,
    wins            INTEGER         NOT NULL,

    CONSTRAINT pk_champion_spell_stat PRIMARY KEY (id)
);

CREATE UNIQUE INDEX idx_champion_spell_stat_dim ON champion_spell_stat (
    champion_id, team_position, season, tier_group, platform_id, queue_id, game_version,
    spell1_id, spell2_id
);
CREATE INDEX idx_champion_spell_stat_champion ON champion_spell_stat (champion_id, team_position);
CREATE INDEX idx_champion_spell_stat_season_queue ON champion_spell_stat (season, queue_id);

COMMENT ON TABLE champion_spell_stat IS '챔피언 소환사 주문 통계 테이블';
COMMENT ON COLUMN champion_spell_stat.id IS '고유 식별자';
COMMENT ON COLUMN champion_spell_stat.champion_id IS '챔피언 ID';
COMMENT ON COLUMN champion_spell_stat.team_position IS '라인';
COMMENT ON COLUMN champion_spell_stat.season IS '시즌 번호';
COMMENT ON COLUMN champion_spell_stat.tier_group IS '티어 그룹';
COMMENT ON COLUMN champion_spell_stat.platform_id IS '지역';
COMMENT ON COLUMN champion_spell_stat.queue_id IS '큐 ID';
COMMENT ON COLUMN champion_spell_stat.game_version IS '패치 버전';
COMMENT ON COLUMN champion_spell_stat.spell1_id IS '소환사 주문1 ID (LEAST 정규화)';
COMMENT ON COLUMN champion_spell_stat.spell2_id IS '소환사 주문2 ID (GREATEST 정규화)';
COMMENT ON COLUMN champion_spell_stat.games IS '판수';
COMMENT ON COLUMN champion_spell_stat.wins IS '승수';


-- -----------------------------------------------------
-- Table: champion_skill_stat
-- Description: 챔피언 스킬 빌드 통계
-- -----------------------------------------------------
CREATE TABLE champion_skill_stat (
    id              BIGINT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    champion_id     INTEGER         NOT NULL,
    team_position   VARCHAR(20)     NOT NULL,
    season          INTEGER         NOT NULL,
    tier_group      VARCHAR(30)     NOT NULL,
    platform_id     VARCHAR(10)     NOT NULL,
    queue_id        INTEGER         NOT NULL,
    game_version    VARCHAR(20)     NOT NULL,
    skill_order     VARCHAR(500)    NOT NULL,
    skill_priority  VARCHAR(20)     NOT NULL,
    games           INTEGER         NOT NULL,
    wins            INTEGER         NOT NULL,

    CONSTRAINT pk_champion_skill_stat PRIMARY KEY (id)
);

CREATE UNIQUE INDEX idx_champion_skill_stat_dim ON champion_skill_stat (
    champion_id, team_position, season, tier_group, platform_id, queue_id, game_version,
    skill_order
);
CREATE INDEX idx_champion_skill_stat_champion ON champion_skill_stat (champion_id, team_position);
CREATE INDEX idx_champion_skill_stat_priority ON champion_skill_stat (champion_id, team_position, skill_priority);
CREATE INDEX idx_champion_skill_stat_season_queue ON champion_skill_stat (season, queue_id);

COMMENT ON TABLE champion_skill_stat IS '챔피언 스킬 빌드 통계 테이블';
COMMENT ON COLUMN champion_skill_stat.id IS '고유 식별자';
COMMENT ON COLUMN champion_skill_stat.champion_id IS '챔피언 ID';
COMMENT ON COLUMN champion_skill_stat.team_position IS '라인';
COMMENT ON COLUMN champion_skill_stat.season IS '시즌 번호';
COMMENT ON COLUMN champion_skill_stat.tier_group IS '티어 그룹';
COMMENT ON COLUMN champion_skill_stat.platform_id IS '지역';
COMMENT ON COLUMN champion_skill_stat.queue_id IS '큐 ID';
COMMENT ON COLUMN champion_skill_stat.game_version IS '패치 버전';
COMMENT ON COLUMN champion_skill_stat.skill_order IS '전체 레벨업 순서 CSV (ex: "1,3,1,2,1,3,...")';
COMMENT ON COLUMN champion_skill_stat.skill_priority IS '스킬 우선순위 요약 (ex: "Q>E>W")';
COMMENT ON COLUMN champion_skill_stat.games IS '판수';
COMMENT ON COLUMN champion_skill_stat.wins IS '승수';


-- -----------------------------------------------------
-- Table: champion_item_stat
-- Description: 챔피언 아이템 빌드 통계
-- -----------------------------------------------------
CREATE TABLE champion_item_stat (
    id              BIGINT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    champion_id     INTEGER         NOT NULL,
    team_position   VARCHAR(20)     NOT NULL,
    season          INTEGER         NOT NULL,
    tier_group      VARCHAR(30)     NOT NULL,
    platform_id     VARCHAR(10)     NOT NULL,
    queue_id        INTEGER         NOT NULL,
    game_version    VARCHAR(20)     NOT NULL,
    build_type      VARCHAR(20)     NOT NULL,
    item_ids        VARCHAR(255)    NOT NULL,
    games           INTEGER         NOT NULL,
    wins            INTEGER         NOT NULL,

    CONSTRAINT pk_champion_item_stat PRIMARY KEY (id)
);

CREATE UNIQUE INDEX idx_champion_item_stat_dim ON champion_item_stat (
    champion_id, team_position, season, tier_group, platform_id, queue_id, game_version,
    build_type, item_ids
);
CREATE INDEX idx_champion_item_stat_champion ON champion_item_stat (champion_id, team_position);
CREATE INDEX idx_champion_item_stat_build ON champion_item_stat (champion_id, team_position, build_type);
CREATE INDEX idx_champion_item_stat_season_queue ON champion_item_stat (season, queue_id);

COMMENT ON TABLE champion_item_stat IS '챔피언 아이템 빌드 통계 테이블';
COMMENT ON COLUMN champion_item_stat.id IS '고유 식별자';
COMMENT ON COLUMN champion_item_stat.champion_id IS '챔피언 ID';
COMMENT ON COLUMN champion_item_stat.team_position IS '라인';
COMMENT ON COLUMN champion_item_stat.season IS '시즌 번호';
COMMENT ON COLUMN champion_item_stat.tier_group IS '티어 그룹';
COMMENT ON COLUMN champion_item_stat.platform_id IS '지역';
COMMENT ON COLUMN champion_item_stat.queue_id IS '큐 ID';
COMMENT ON COLUMN champion_item_stat.game_version IS '패치 버전';
COMMENT ON COLUMN champion_item_stat.build_type IS '빌드 유형 (STARTER, BOOTS, CORE)';
COMMENT ON COLUMN champion_item_stat.item_ids IS '정렬된 아이템 ID CSV';
COMMENT ON COLUMN champion_item_stat.games IS '판수';
COMMENT ON COLUMN champion_item_stat.wins IS '승수';


-- -----------------------------------------------------
-- Table: champion_matchup_stat
-- Description: 챔피언 상대 매치업 통계
-- -----------------------------------------------------
CREATE TABLE champion_matchup_stat (
    id                      BIGINT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    champion_id             INTEGER         NOT NULL,
    team_position           VARCHAR(20)     NOT NULL,
    season                  INTEGER         NOT NULL,
    tier_group              VARCHAR(30)     NOT NULL,
    platform_id             VARCHAR(10)     NOT NULL,
    queue_id                INTEGER         NOT NULL,
    game_version            VARCHAR(20)     NOT NULL,
    opponent_champion_id    INTEGER         NOT NULL,
    games                   INTEGER         NOT NULL,
    wins                    INTEGER         NOT NULL,
    avg_kills               DECIMAL(5,2)    NOT NULL,
    avg_deaths              DECIMAL(5,2)    NOT NULL,
    avg_assists             DECIMAL(5,2)    NOT NULL,
    avg_gold_diff           DECIMAL(9,2)    NOT NULL,

    CONSTRAINT pk_champion_matchup_stat PRIMARY KEY (id)
);

CREATE UNIQUE INDEX idx_champion_matchup_stat_dim ON champion_matchup_stat (
    champion_id, team_position, season, tier_group, platform_id, queue_id, game_version,
    opponent_champion_id
);
CREATE INDEX idx_champion_matchup_stat_champion ON champion_matchup_stat (champion_id, team_position);
CREATE INDEX idx_champion_matchup_stat_opponent ON champion_matchup_stat (opponent_champion_id);
CREATE INDEX idx_champion_matchup_stat_season_queue ON champion_matchup_stat (season, queue_id);

COMMENT ON TABLE champion_matchup_stat IS '챔피언 상대 매치업 통계 테이블';
COMMENT ON COLUMN champion_matchup_stat.id IS '고유 식별자';
COMMENT ON COLUMN champion_matchup_stat.champion_id IS '챔피언 ID';
COMMENT ON COLUMN champion_matchup_stat.team_position IS '라인';
COMMENT ON COLUMN champion_matchup_stat.season IS '시즌 번호';
COMMENT ON COLUMN champion_matchup_stat.tier_group IS '티어 그룹';
COMMENT ON COLUMN champion_matchup_stat.platform_id IS '지역';
COMMENT ON COLUMN champion_matchup_stat.queue_id IS '큐 ID';
COMMENT ON COLUMN champion_matchup_stat.game_version IS '패치 버전';
COMMENT ON COLUMN champion_matchup_stat.opponent_champion_id IS '상대 챔피언 ID';
COMMENT ON COLUMN champion_matchup_stat.games IS '판수';
COMMENT ON COLUMN champion_matchup_stat.wins IS '승수';
COMMENT ON COLUMN champion_matchup_stat.avg_kills IS '평균 킬';
COMMENT ON COLUMN champion_matchup_stat.avg_deaths IS '평균 데스';
COMMENT ON COLUMN champion_matchup_stat.avg_assists IS '평균 어시스트';
COMMENT ON COLUMN champion_matchup_stat.avg_gold_diff IS '상대 대비 평균 골드 차이';


-- =====================================================
-- 집계 쿼리 성능을 위한 기존 테이블 인덱스
-- =====================================================
-- 이미 존재하는 인덱스와 중복 여부를 확인한 후 실행할 것

CREATE INDEX IF NOT EXISTS idx_ms_match_champ_pos ON match_summoner (match_id, champion_id, team_position);
CREATE INDEX IF NOT EXISTS idx_ms_champ_pos ON match_summoner (champion_id, team_position);
CREATE INDEX IF NOT EXISTS idx_match_season_queue ON match (season, queue_id);
CREATE INDEX IF NOT EXISTS idx_ls_puuid_queue ON league_summoner (puuid, queue);
