package com.example.lolserver.domain.league.domain.vo;

import java.time.LocalDateTime;

public record LeagueHistory(
    Long leagueSummonerId,
    String puuid,
    String queue,
    String leagueId,
    int wins,
    int losses,
    String tier,
    String rank,
    int leaguePoints,
    long absolutePoints,
    boolean veteran,
    boolean inactive,
    boolean freshBlood,
    boolean hotStreak,
    LocalDateTime createdAt
) {
    // Constructor will be automatically generated by record
}
