spring:
  config:
    import:
      - core-prod.yml
      - api-prod.yml
      - client-repository-prod.yml
      - oauth-prod.yml
      - rabbitmq-prod.yml
      - kafka-prod.yml
      - postgresql-prod.yml
      - redis-prod.yml
      - bigquery-prod.yml
      - logging-prod.yml
