message:
  broker: rabbitmq

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
  config:
    import:
      - core.yml
      - api.yml
      - oauth.yml
      - client-repository.yml
      - rabbitmq.yml
      - kafka.yml
      - postgresql.yml
      - redis.yml
      - bigquery.yml
      - logging.yml
