message:
  broker: rabbitmq

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

---
spring:
  config:
    activate:
      on-profile: local
    import:
      - core-local.yml
      - api-local.yml
      - client-repository-local.yml
      - oauth-local.yml
      - rabbitmq-local.yml
      - kafka-local.yml
      - postgresql-local.yml
      - redis-local.yml
      - clickhouse-local.yml
      - logging-local.yml

---
spring:
  config:
    activate:
      on-profile: dev
    import:
      - core-dev.yml
      - api-dev.yml
      - client-repository-dev.yml
      - rabbitmq-dev.yml
      - kafka-dev.yml
      - postgresql-dev.yml
      - redis-dev.yml
      - clickhouse-dev.yml

---
spring:
  config:
    activate:
      on-profile: prod
    import:
      - core-prod.yml
      - api-prod.yml
      - client-repository-prod.yml
      - rabbitmq-prod.yml
      - kafka-prod.yml
      - postgresql-prod.yml
      - redis-prod.yml
      - clickhouse-prod.yml
