spring:
  config:
    import:
      - core-dev.yml
      - api-dev.yml
      - client-repository-dev.yml
      - oauth-dev.yml
      - rabbitmq-dev.yml
      - kafka-dev.yml
      - postgresql-dev.yml
      - redis-dev.yml
      - bigquery-dev.yml
      - logging-dev.yml
