plugins {
    id 'lolserver.web-conventions'
    id 'lolserver.persistence-conventions'
}

dependencies {
    implementation project(':module:common')
    implementation project(':module:shared')

    testImplementation(testFixtures(project(':module:common')))
    testImplementation 'com.tngtech.archunit:archunit-junit5:1.3.0'
}
